{
  "swagger": "2.0",
  "info": {
    "description": "Translation TBD",
    "version": "2.1.0-0",
    "title": "REST-api for Naturv√•rdsregistret"
  },
  "basePath": "/naturvardsregistret/v2/rest",
  "schemes": [],
  "tags": [
    {
      "name": "BeslutsdokumentService"
    },
    {
      "name": "ForeskriftsomradesService"
    },
    {
      "name": "ForeskriftssubtyperService"
    },
    {
      "name": "ForeskriftstyperService"
    },
    {
      "name": "MiljomalService"
    },
    {
      "name": "NmdKlassService"
    },
    {
      "name": "OmradeService"
    },
    {
      "name": "StatusServiceBean"
    },
    {
      "name": "SyfteService"
    },
    {
      "name": "SyftenService"
    }
  ],
  "definitions": {
    "Beslutsdokument": {
      "type": "object",
      "title": "Beslutsdokument",
      "properties": {
        "nvrId": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsId": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsstatus": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutstyp": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsmyndighet": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "diarienummer": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsdatum": {
          "readOnly": false,
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "gallandedatum": {
          "readOnly": false,
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "id": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "namn": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "typ": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "mimeType": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "fileUrl": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "atomLink": {
          "readOnly": false,
          "description": "",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      },
      "example": {
        "nvrId": "...",
        "beslutsId": "...",
        "beslutsstatus": "...",
        "beslutstyp": "...",
        "beslutsmyndighet": "...",
        "diarienummer": "...",
        "beslutsdatum": 12345,
        "gallandedatum": 12345,
        "id": "...",
        "namn": "...",
        "typ": "...",
        "mimeType": "...",
        "fileUrl": "...",
        "atomLink": [
          {},
          {}
        ]
      },
      "description": ""
    },
    "Foreskriftsomrade": {
      "type": "object",
      "title": "Foreskriftsomrade",
      "properties": {
        "objectId": {
          "readOnly": false,
          "description": "",
          "type": "integer",
          "format": "int64"
        },
        "nvrId": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsstatus": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "foreskriftstyp": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "foreskriftssubtyp": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "franDatum": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "tillDatum": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "areaHa": {
          "readOnly": false,
          "description": "",
          "type": "number"
        },
        "foreskriftstypKod": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "foreskriftssubtypKod": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "atomLink": {
          "readOnly": false,
          "description": "",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      },
      "example": {
        "objectId": 12345,
        "nvrId": "...",
        "beslutsstatus": "...",
        "foreskriftstyp": "...",
        "foreskriftssubtyp": "...",
        "franDatum": "...",
        "tillDatum": "...",
        "areaHa": 12345,
        "foreskriftstypKod": "...",
        "foreskriftssubtypKod": "...",
        "atomLink": [
          {},
          {}
        ]
      },
      "description": ""
    },
    "Miljomal": {
      "type": "object",
      "title": "Miljomal",
      "properties": {
        "nvrId": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsstatus": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "namn": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "atomLink": {
          "readOnly": false,
          "description": "",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      },
      "example": {
        "nvrId": "...",
        "beslutsstatus": "...",
        "namn": "...",
        "atomLink": [
          {},
          {}
        ]
      },
      "description": ""
    },
    "NmdKlass": {
      "type": "object",
      "title": "NmdKlass",
      "properties": {
        "nvrId": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsstatus": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "kod": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "foreskriftstyp": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "namn": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "areaHa": {
          "readOnly": false,
          "description": "",
          "type": "number"
        },
        "foreskriftstypNamn": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "atomLink": {
          "readOnly": false,
          "description": "",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      },
      "example": {
        "nvrId": "...",
        "beslutsstatus": "...",
        "kod": "...",
        "foreskriftstyp": "...",
        "namn": "...",
        "areaHa": 12345,
        "foreskriftstypNamn": "...",
        "atomLink": [
          {},
          {}
        ]
      },
      "description": ""
    },
    "OmradeDto": {
      "type": "object",
      "title": "Omrade",
      "properties": {
        "id": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsstatus": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "namn": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "skyddstyp": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "lanAsText": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "kommunerAsText": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutstyp": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsdatum": {
          "readOnly": false,
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "ursprBeslutsdatum": {
          "readOnly": false,
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "gallandedatum": {
          "readOnly": false,
          "description": "",
          "type": "integer",
          "format": "int32"
        },
        "iucnKategori": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "forvaltare": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "areaHa": {
          "readOnly": false,
          "description": "",
          "type": "number"
        },
        "landareaHa": {
          "readOnly": false,
          "description": "",
          "type": "number"
        },
        "vattenareaHa": {
          "readOnly": false,
          "description": "",
          "type": "number"
        },
        "skogAreaHa": {
          "readOnly": false,
          "description": "",
          "type": "number"
        },
        "beslutsmyndighet": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "atomLink": {
          "readOnly": false,
          "description": "",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      },
      "example": {
        "id": "...",
        "beslutsstatus": "...",
        "namn": "...",
        "skyddstyp": "...",
        "lanAsText": "...",
        "kommunerAsText": "...",
        "beslutstyp": "...",
        "beslutsdatum": 12345,
        "ursprBeslutsdatum": 12345,
        "gallandedatum": 12345,
        "iucnKategori": "...",
        "forvaltare": "...",
        "areaHa": 12345,
        "landareaHa": 12345,
        "vattenareaHa": 12345,
        "skogAreaHa": 12345,
        "beslutsmyndighet": "...",
        "atomLink": [
          {},
          {}
        ]
      },
      "description": ""
    },
    "Syfte": {
      "type": "object",
      "title": "Syfte",
      "properties": {
        "nvrId": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beslutsstatus": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "id": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "namn": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "beskrivning": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "atomLink": {
          "readOnly": false,
          "description": "",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      },
      "example": {
        "nvrId": "...",
        "beslutsstatus": "...",
        "id": "...",
        "namn": "...",
        "beskrivning": "...",
        "atomLink": [
          {},
          {}
        ]
      },
      "description": ""
    },
    "Typ": {
      "type": "object",
      "title": "Typ",
      "properties": {
        "key": {
          "readOnly": false,
          "description": "",
          "type": "string"
        },
        "value": {
          "readOnly": false,
          "description": "",
          "type": "string"
        }
      },
      "example": {
        "key": "...",
        "value": "..."
      },
      "description": ""
    }
  },
  "paths": {
    "/beslutsdokument/ping": {
      "head": {
        "tags": [
          "BeslutsdokumentService"
        ],
        "operationId": "isOk",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        }
      }
    },
    "/beslutsdokument/{nvrId}/{beslutsstatus}/{id}": {
      "get": {
        "tags": [
          "BeslutsdokumentService"
        ],
        "description": "Returnerar ett beslutsdokument f√∂r ett specifikt omr√•de.",
        "operationId": "get",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "Id"
          },
          {
            "name": "nvrId",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r ett omr√•de"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Beslutsdokument",
              "description": "Beslutsdokument"
            },
            "examples": {
              "application/json": {
                "nvrId": "...",
                "beslutsId": "...",
                "beslutsstatus": "...",
                "beslutstyp": "...",
                "beslutsmyndighet": "...",
                "diarienummer": "...",
                "beslutsdatum": 12345,
                "gallandedatum": 12345,
                "id": "...",
                "namn": "...",
                "typ": "...",
                "mimeType": "...",
                "fileUrl": "...",
                "atomLink": [
                  {},
                  {}
                ]
              }
            },
            "description": "Beslutsdokument"
          }
        }
      }
    },
    "/foreskriftsomrade/ping": {
      "head": {
        "tags": [
          "ForeskriftsomradesService"
        ],
        "operationId": "isOk2",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        }
      }
    },
    "/foreskriftsomrade/{nvrId}/{beslutsstatus}/{objectid}": {
      "get": {
        "tags": [
          "ForeskriftsomradesService"
        ],
        "description": "Returnerar ett f√∂reskriftsomr√•de f√∂r ett specifikt omr√•de.",
        "operationId": "get2",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de"
          },
          {
            "name": "nvrId",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r ett omr√•de"
          },
          {
            "name": "objectid",
            "in": "path",
            "type": "integer",
            "format": "int64",
            "description": "Objectid"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Foreskriftsomrade",
              "description": "Foreskriftsomrade"
            },
            "examples": {
              "application/json": {
                "objectId": 12345,
                "nvrId": "...",
                "beslutsstatus": "...",
                "foreskriftstyp": "...",
                "foreskriftssubtyp": "...",
                "franDatum": "...",
                "tillDatum": "...",
                "areaHa": 12345,
                "foreskriftstypKod": "...",
                "foreskriftssubtypKod": "...",
                "atomLink": [
                  {},
                  {}
                ]
              }
            },
            "description": "Foreskriftsomrade"
          }
        }
      }
    },
    "/foreskriftssubtyper": {
      "get": {
        "tags": [
          "ForeskriftssubtyperService"
        ],
        "description": "Returnerar en lista av f√∂reskriftssubtyper.\nF√∂reskriftssubtyper kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getForeskriftsSubtyperList",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Typ)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List(Typ)"
          }
        }
      }
    },
    "/foreskriftstyper": {
      "get": {
        "tags": [
          "ForeskriftstyperService"
        ],
        "description": "Returnerar en lista av f√∂reskriftstyper.\nF√∂reskriftstyper kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getForeskrifterList",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Typ)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List(Typ)"
          }
        }
      }
    },
    "/miljomal": {
      "get": {
        "tags": [
          "MiljomalService"
        ],
        "description": "Returnerar en lista av milj√∂m√•l.\nMilj√∂m√•l som retuneras kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den",
        "operationId": "getMiljomalList",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Typ)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List(Typ)"
          }
        }
      }
    },
    "/miljomal/ping": {
      "head": {
        "tags": [
          "MiljomalService"
        ],
        "operationId": "isOk3",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        }
      }
    },
    "/miljomal/{nvrId}/{beslutsstatus}/{namn}": {
      "get": {
        "tags": [
          "MiljomalService"
        ],
        "description": "Returnerar ett milj√∂m√•l f√∂r ett omr√•de.",
        "operationId": "get3",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": ""
          },
          {
            "name": "namn",
            "in": "path",
            "type": "string",
            "description": ""
          },
          {
            "name": "nvrId",
            "in": "path",
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Miljomal",
              "description": "Miljomal"
            },
            "examples": {
              "application/json": {
                "nvrId": "...",
                "beslutsstatus": "...",
                "namn": "...",
                "atomLink": [
                  {},
                  {}
                ]
              }
            },
            "description": "Miljomal"
          }
        }
      }
    },
    "/nmdklass": {
      "get": {
        "tags": [
          "NmdKlassService"
        ],
        "description": "Returnerar en lista √∂ver alla NndKlasser som anv√§nds inom nvr-omr√•den.\nNndKlasserna som returneras √§r giltiga som s√∂kparameter i en s√∂kning av nvr-omr√•den.\n\nReturnerat data kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getNmdKlasser",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List<Typ>",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List<Typ>"
          }
        }
      }
    },
    "/nmdklass/niva1": {
      "get": {
        "tags": [
          "NmdKlassService"
        ],
        "description": "Returnerar en lista √∂ver alla NmdKlasser p√• niv√• 1 som anv√§nds inom nvr-omr√•den.\nNmdKlasserna som returneras √§r giltiga som s√∂kparameter i en s√∂kning av nvr-omr√•den.\n\nReturnerat data kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getNmdKlasserNiva1List",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List<Typ>",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List<Typ>"
          }
        }
      }
    },
    "/nmdklass/niva2": {
      "get": {
        "tags": [
          "NmdKlassService"
        ],
        "description": "Returnerar en lista √∂ver alla NmdKlasser p√• niv√• 2 som anv√§nds inom nvr-omr√•den.\nNmdKlasserna som returneras √§r giltiga som s√∂kparameter i en s√∂kning av nvr-omr√•den.\n\nReturnerat data kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getNmdKlasserNiva2List",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List<Typ>",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List<Typ>"
          }
        }
      }
    },
    "/nmdklass/niva3": {
      "get": {
        "tags": [
          "NmdKlassService"
        ],
        "description": "Returnerar en lista √∂ver alla NmdKlasser p√• niv√• 3 som anv√§nds inom nvr-omr√•den.\nNmdKlasserna som returneras √§r giltiga som s√∂kparameter i en s√∂kning av nvr-omr√•den.\n\nReturnerat data kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getNmdKlasserNiva3List",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List<Typ>",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List<Typ>"
          }
        }
      }
    },
    "/nmdklass/ping": {
      "head": {
        "tags": [
          "NmdKlassService"
        ],
        "operationId": "isOk4",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        }
      }
    },
    "/nmdklass/{nvrId}/{beslutsstatus}/{nmdKlassKod}": {
      "get": {
        "tags": [
          "NmdKlassService"
        ],
        "description": "Returnerar en NmdKlass.",
        "operationId": "getOmradesNmdKlasser",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus from Omrade"
          },
          {
            "name": "nmdKlassKod",
            "in": "path",
            "type": "string",
            "description": "NmdKlassKod"
          },
          {
            "name": "nvrId",
            "in": "path",
            "type": "string",
            "description": "NvrId from Omrade"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/NmdKlass",
              "description": "NmdKlass"
            },
            "examples": {
              "application/json": {
                "nvrId": "...",
                "beslutsstatus": "...",
                "kod": "...",
                "foreskriftstyp": "...",
                "namn": "...",
                "areaHa": 12345,
                "foreskriftstypNamn": "...",
                "atomLink": [
                  {},
                  {}
                ]
              }
            },
            "description": "NmdKlass"
          }
        }
      }
    },
    "/omrade": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista med omr√•den.",
        "operationId": "find",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsdatum_from",
            "in": "query",
            "type": "string",
            "description": "Beslutsdatum (from) (yyyy-MM-dd)"
          },
          {
            "name": "beslutsdatum_tom",
            "in": "query",
            "type": "string",
            "description": "Beslutsdatum (to) (yyyy-MM-dd)"
          },
          {
            "name": "beslutsmyndighet",
            "in": "query",
            "type": "string",
            "description": "Beslutsmyndighet"
          },
          {
            "name": "beslutsstatus",
            "in": "query",
            "type": "string",
            "description": "Beslutsstatus (Beslutad, √ñverklagad, G√§llande)"
          },
          {
            "name": "foreskriftssubtyp",
            "in": "query",
            "type": "string",
            "description": "F√∂reskriftssubtyp"
          },
          {
            "name": "foreskriftstyp",
            "in": "query",
            "type": "string",
            "description": "F√∂reskriftstyp"
          },
          {
            "name": "forstagangsbeslut",
            "in": "query",
            "default": "false",
            "type": "boolean",
            "description": "F√∂rstag√•ngsbeslut"
          },
          {
            "name": "gallandedatum_from",
            "in": "query",
            "type": "string",
            "description": "G√§llandedatum (from) (yyyy-MM-dd)"
          },
          {
            "name": "gallandedatum_tom",
            "in": "query",
            "type": "string",
            "description": "G√§llandedatum (to) (yyyy-MM-dd)"
          },
          {
            "name": "id",
            "in": "query",
            "type": "string",
            "description": "NvrId. Beh√∂ver inte vara hela utan s√∂kes som ett prefix."
          },
          {
            "name": "kommun",
            "in": "query",
            "type": "string",
            "description": "Kommunkoden T.ex. 2580 f√∂r Lule√•."
          },
          {
            "name": "lan",
            "in": "query",
            "type": "string",
            "description": "L√§nskoden. T.ex. BD f√∂r Norrbotten."
          },
          {
            "name": "limit",
            "in": "query",
            "default": "100",
            "type": "integer",
            "format": "int32",
            "description": "En gr√§ns f√∂r hur m√•nga resultat som ska returneras."
          },
          {
            "name": "miljomal",
            "in": "query",
            "type": "string",
            "description": "Milj√∂m√•l"
          },
          {
            "name": "namn",
            "in": "query",
            "type": "string",
            "description": "Namnet p√• omr√•det. Beh√∂ver inte vara hela utan s√∂kes som ett prefix."
          },
          {
            "name": "nmdklasskod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "nmdklassniva1kod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod p√• niv√• 1. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "nmdklassniva2kod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod p√• niv√• 2. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "nmdklassniva3kod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod p√• niv√• 3. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "skyddstypkod",
            "in": "query",
            "type": "string",
            "description": "Skyddstypkod"
          },
          {
            "name": "skyddstypnamn",
            "in": "query",
            "type": "string",
            "description": "Skyddstypnamn"
          },
          {
            "name": "syfte",
            "in": "query",
            "type": "string",
            "description": "Syfte"
          },
          {
            "name": "ursprBeslutsdatum_from",
            "in": "query",
            "type": "string",
            "description": "Ursprungligt beslutsdatum (from) (yyyy-MM-dd)"
          },
          {
            "name": "ursprBeslutsdatum_tom",
            "in": "query",
            "type": "string",
            "description": "Ursprungligt beslutsdatum (to) (yyyy-MM-dd)"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Omrade)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/OmradeDto"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": "...",
                  "beslutsstatus": "...",
                  "namn": "...",
                  "skyddstyp": "...",
                  "lanAsText": "...",
                  "kommunerAsText": "...",
                  "beslutstyp": "...",
                  "beslutsdatum": 12345,
                  "ursprBeslutsdatum": 12345,
                  "gallandedatum": 12345,
                  "iucnKategori": "...",
                  "forvaltare": "...",
                  "areaHa": 12345,
                  "landareaHa": 12345,
                  "vattenareaHa": 12345,
                  "skogAreaHa": 12345,
                  "beslutsmyndighet": "...",
                  "atomLink": [
                    {},
                    {}
                  ]
                }
              ]
            },
            "description": "List(Omrade)"
          }
        }
      }
    },
    "/omrade/beslutsmyndigheter": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista av beslutsmyndigheter som kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getBeslutsmyndighetList",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Typ)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List(Typ)"
          }
        }
      }
    },
    "/omrade/beslutsstatusar": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista av beslutsstatusar som kan anv√§ndas som s√∂kparameter vid s√∂kning av omr√•den.",
        "operationId": "getBeslutsstatusList",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Typ)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List(Typ)"
          }
        }
      }
    },
    "/omrade/extentAsWkt": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar ett omr√•des geometriers extent (som wkt).\nAnv√§nder bara id, ej beslutsstatus.\nInte helt korrekt (pga optimering). Ska ge r√§tt resultat i de flesta fall.",
        "operationId": "extentAsWkt",
        "produces": [
          "text/plain;charset=utf-8"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "description": "Id"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "String",
              "type": "string"
            },
            "description": "String"
          }
        }
      }
    },
    "/omrade/nolinks": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista med omr√•den.\nResultatet inneh√•ller inte l√§nkar till underresurser (t.ex. NmdKlasser).",
        "operationId": "findNoLinks",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsdatum_from",
            "in": "query",
            "type": "string",
            "description": "Beslutsdatum (from) (yyyy-MM-dd)"
          },
          {
            "name": "beslutsdatum_tom",
            "in": "query",
            "type": "string",
            "description": "Beslutsdatum (to) (yyyy-MM-dd)"
          },
          {
            "name": "beslutsmyndighet",
            "in": "query",
            "type": "string",
            "description": "Beslutsmyndighet"
          },
          {
            "name": "beslutsstatus",
            "in": "query",
            "type": "string",
            "description": "Beslutsstatus (Beslutad, √ñverklagad, G√§llande)"
          },
          {
            "name": "foreskriftssubtyp",
            "in": "query",
            "type": "string",
            "description": "F√∂reskriftssubtyp"
          },
          {
            "name": "foreskriftstyp",
            "in": "query",
            "type": "string",
            "description": "F√∂reskriftstyp"
          },
          {
            "name": "forstagangsbeslut",
            "in": "query",
            "default": "false",
            "type": "boolean",
            "description": "F√∂rstag√•ngsbeslut"
          },
          {
            "name": "gallandedatum_from",
            "in": "query",
            "type": "string",
            "description": "G√§llandedatum (from) (yyyy-MM-dd)"
          },
          {
            "name": "gallandedatum_tom",
            "in": "query",
            "type": "string",
            "description": "G√§llandedatum (to) (yyyy-MM-dd)"
          },
          {
            "name": "id",
            "in": "query",
            "type": "string",
            "description": "NvrId. Beh√∂ver inte vara hela utan s√∂kes som ett prefix."
          },
          {
            "name": "kommun",
            "in": "query",
            "type": "string",
            "description": "Kommunkoden T.ex. 2580 f√∂r Lule√•."
          },
          {
            "name": "lan",
            "in": "query",
            "type": "string",
            "description": "L√§nskoden. T.ex. BD f√∂r Norrbotten."
          },
          {
            "name": "limit",
            "in": "query",
            "default": "100",
            "type": "integer",
            "format": "int32",
            "description": "En gr√§ns f√∂r hur m√•nga resultat som ska returneras."
          },
          {
            "name": "miljomal",
            "in": "query",
            "type": "string",
            "description": "Milj√∂m√•l"
          },
          {
            "name": "namn",
            "in": "query",
            "type": "string",
            "description": "Namnet p√• omr√•det. Beh√∂ver inte vara hela utan s√∂kes som ett prefix."
          },
          {
            "name": "nmdklasskod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "nmdklassniva1kod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod p√• niv√• 1. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "nmdklassniva2kod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod p√• niv√• 2. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "nmdklassniva3kod",
            "in": "query",
            "type": "string",
            "description": "nmdklasskod p√• niv√• 3. Kan h√§mtas via NmdKlassService."
          },
          {
            "name": "skyddstypkod",
            "in": "query",
            "type": "string",
            "description": "Skyddstypkod"
          },
          {
            "name": "skyddstypnamn",
            "in": "query",
            "type": "string",
            "description": "Skyddstypnamn"
          },
          {
            "name": "syfte",
            "in": "query",
            "type": "string",
            "description": "Syfte"
          },
          {
            "name": "ursprBeslutsdatum_from",
            "in": "query",
            "type": "string",
            "description": "Ursprungligt beslutsdatum (from) (yyyy-MM-dd)"
          },
          {
            "name": "ursprBeslutsdatum_tom",
            "in": "query",
            "type": "string",
            "description": "Ursprungligt beslutsdatum (to) (yyyy-MM-dd)"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Omrade)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/OmradeDto"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": "...",
                  "beslutsstatus": "...",
                  "namn": "...",
                  "skyddstyp": "...",
                  "lanAsText": "...",
                  "kommunerAsText": "...",
                  "beslutstyp": "...",
                  "beslutsdatum": 12345,
                  "ursprBeslutsdatum": 12345,
                  "gallandedatum": 12345,
                  "iucnKategori": "...",
                  "forvaltare": "...",
                  "areaHa": 12345,
                  "landareaHa": 12345,
                  "vattenareaHa": 12345,
                  "skogAreaHa": 12345,
                  "beslutsmyndighet": "...",
                  "atomLink": [
                    {},
                    {}
                  ]
                }
              ]
            },
            "description": "List(Omrade)"
          }
        }
      }
    },
    "/omrade/ping": {
      "head": {
        "tags": [
          "OmradeService"
        ],
        "operationId": "isOk5",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        }
      }
    },
    "/omrade/skyddstyper": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista av Skyddstyper.\nSkyddstyper som returneras √§r giltiga som s√∂kparameter vid s√∂kning av omr√•den",
        "operationId": "getSkyddstyperList",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Typ)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List(Typ)"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar ett omr√•de.",
        "operationId": "get4",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "NVR-id"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/OmradeDto",
              "description": "Omrade"
            },
            "examples": {
              "application/json": {
                "id": "...",
                "beslutsstatus": "...",
                "namn": "...",
                "skyddstyp": "...",
                "lanAsText": "...",
                "kommunerAsText": "...",
                "beslutstyp": "...",
                "beslutsdatum": 12345,
                "ursprBeslutsdatum": 12345,
                "gallandedatum": 12345,
                "iucnKategori": "...",
                "forvaltare": "...",
                "areaHa": 12345,
                "landareaHa": 12345,
                "vattenareaHa": 12345,
                "skogAreaHa": 12345,
                "beslutsmyndighet": "...",
                "atomLink": [
                  {},
                  {}
                ]
              }
            },
            "description": "Omrade"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}/beslutsdokument": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista med beslutsdokument f√∂r ett specifikt omr√•de",
        "operationId": "getOmradesBeslutsdokument",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de,"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r ett omr√•de,"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Beslutsdokument)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Beslutsdokument"
              }
            },
            "examples": {
              "application/json": [
                {
                  "nvrId": "...",
                  "beslutsId": "...",
                  "beslutsstatus": "...",
                  "beslutstyp": "...",
                  "beslutsmyndighet": "...",
                  "diarienummer": "...",
                  "beslutsdatum": 12345,
                  "gallandedatum": 12345,
                  "id": "...",
                  "namn": "...",
                  "typ": "...",
                  "mimeType": "...",
                  "fileUrl": "...",
                  "atomLink": [
                    {},
                    {}
                  ]
                }
              ]
            },
            "description": "List(Beslutsdokument)"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}/extentAsWkt": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar extent (som wkt) f√∂r geometrin f√∂r ett omr√•de.",
        "operationId": "extentAsWkt",
        "produces": [
          "text/plain;charset=utf-8"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutssatus"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "Id"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "String",
              "type": "string"
            },
            "description": "String"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}/foreskriftsomraden": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista av f√∂reskriftsomr√•den f√∂r ett specifikt omr√•de.",
        "operationId": "getOmradesForeskriftsomraden",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de,"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r ett omr√•de,"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Syfte)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Foreskriftsomrade"
              }
            },
            "examples": {
              "application/json": [
                {
                  "objectId": 12345,
                  "nvrId": "...",
                  "beslutsstatus": "...",
                  "foreskriftstyp": "...",
                  "foreskriftssubtyp": "...",
                  "franDatum": "...",
                  "tillDatum": "...",
                  "areaHa": 12345,
                  "foreskriftstypKod": "...",
                  "foreskriftssubtypKod": "...",
                  "atomLink": [
                    {},
                    {}
                  ]
                }
              ]
            },
            "description": "List(Syfte)"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}/miljomal": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista av milj√∂m√•l f√∂r ett specifikt omr√•de",
        "operationId": "getOmradesMiljomal",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de,"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r omr√•det,"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Syfte)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Miljomal"
              }
            },
            "examples": {
              "application/json": [
                {
                  "nvrId": "...",
                  "beslutsstatus": "...",
                  "namn": "...",
                  "atomLink": [
                    {},
                    {}
                  ]
                }
              ]
            },
            "description": "List(Syfte)"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}/nmdklasser": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista av NmdKlasser som finns inom ett specifikt nvr-omr√•de.",
        "operationId": "getOmradesNaturtypNmd",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de,"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r ett omr√•de,"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "List(NmdKlass)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/NmdKlass"
              }
            },
            "examples": {
              "application/json": [
                {
                  "nvrId": "...",
                  "beslutsstatus": "...",
                  "kod": "...",
                  "foreskriftstyp": "...",
                  "namn": "...",
                  "areaHa": 12345,
                  "foreskriftstypNamn": "...",
                  "atomLink": [
                    {},
                    {}
                  ]
                }
              ]
            },
            "description": "List(NmdKlass)"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}/syften": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar en lista av syften f√∂r ett specifikt omr√•de.",
        "operationId": "getOmradesSyften",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de,"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r ett omr√•de,"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Syfte)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Syfte"
              }
            },
            "examples": {
              "application/json": [
                {
                  "nvrId": "...",
                  "beslutsstatus": "...",
                  "id": "...",
                  "namn": "...",
                  "beskrivning": "...",
                  "atomLink": [
                    {},
                    {}
                  ]
                }
              ]
            },
            "description": "List(Syfte)"
          }
        }
      }
    },
    "/omrade/{id}/{beslutsstatus}/wkt": {
      "get": {
        "tags": [
          "OmradeService"
        ],
        "description": "Returnerar geometri (som wkt) f√∂r ett omr√•de.",
        "operationId": "wkt",
        "produces": [
          "text/plain;charset=utf-8"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "Id"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "description": "String",
              "type": "string"
            },
            "description": "String"
          }
        }
      }
    },
    "/status/ping": {
      "head": {
        "tags": [
          "StatusServiceBean"
        ],
        "description": "Ping request for att kontrollera om tjansten ar tillganglig",
        "operationId": "isOk6",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "True om allt ok, annars False, i response header 'Ping-Status'. Dessutom returneras HTTP 200 om metoden anropas",
              "type": "file"
            },
            "description": "True om allt ok, annars False, i response header 'Ping-Status'. Dessutom returneras HTTP 200 om metoden anropas"
          }
        }
      }
    },
    "/syfte/ping": {
      "head": {
        "tags": [
          "SyfteService"
        ],
        "operationId": "isOk7",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        }
      }
    },
    "/syfte/{nvrId}/{beslutsstatus}/{id}": {
      "get": {
        "tags": [
          "SyfteService"
        ],
        "description": "Returnerar ett syfte f√∂r ett specifikt omr√•de",
        "operationId": "get5",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "beslutsstatus",
            "in": "path",
            "type": "string",
            "description": "Beslutsstatus f√∂r ett omr√•de"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "Id"
          },
          {
            "name": "nvrId",
            "in": "path",
            "type": "string",
            "description": "NVR-id f√∂r ett omr√•de."
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Syfte",
              "description": "Syfte"
            },
            "examples": {
              "application/json": {
                "nvrId": "...",
                "beslutsstatus": "...",
                "id": "...",
                "namn": "...",
                "beskrivning": "...",
                "atomLink": [
                  {},
                  {}
                ]
              }
            },
            "description": "Syfte"
          }
        }
      }
    },
    "/syften": {
      "get": {
        "tags": [
          "SyftenService"
        ],
        "description": "Returnerar en lista av Syften.\nSyften som returneras √§r giltiga som s√∂kparameter vid s√∂kning av omr√•den",
        "operationId": "getSyftenList",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "List(Typ)",
              "type": "array",
              "items": {
                "$ref": "#/definitions/Typ"
              }
            },
            "examples": {
              "application/json": [
                {
                  "key": "...",
                  "value": "..."
                }
              ]
            },
            "description": "List(Typ)"
          }
        }
      }
    },
    "/syften/ping": {
      "head": {
        "tags": [
          "SyftenService"
        ],
        "operationId": "isOk8",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        }
      }
    }
  }
}